[workspace]
default-members = [
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
members = [
    "examples/*",
    "postgresql_archive",
    "postgresql_commands",
    "postgresql_embedded",
    "postgresql_extensions",
]
resolver = "2"

[workspace.package]
authors = ["Brian Heineman <brian.heineman@gmail.com>"]
categories = ["database"]
edition = "2024"
keywords = ["postgresql", "postgres", "embedded", "database", "server"]
license = "(Apache-2.0 OR MIT) AND PostgreSQL"
repository = "https://github.com/theseus-rs/postgresql-embedded"
rust-version = "1.85.0"
version = "0.17.5"

[workspace.dependencies]
anyhow = "1.0.96"
async-trait = "0.1.86"
axum = "0.8.1"
criterion = "0.5.1"
diesel = "2.2.7"
diesel_migrations = "2.2.0"
flate2 = "1.0.35"
futures-util = "0.3.30"
hex = "0.4.3"
indicatif = "0.17.11"
indoc = "2.0.5"
liblzma = "0.3.6"
md-5 = "0.10.6"
num-format = "0.4.4"
pgvector = "0.4.0"
postgres = "0.19.10"
quick-xml = "0.37.1"
r2d2_postgres = "0.18.1"
rand = "0.9.0"
regex-lite = "0.1.6"
reqwest = { version = "0.12.12", default-features = false }
reqwest-middleware = "0.4.0"
reqwest-retry = "0.7.0"
reqwest-tracing = "0.5.5"
semver = "1.0.25"
serde = "1.0.217"
serde_json = "1.0.138"
sha1 = "0.10.6"
sha2 = "0.10.8"
sqlx = { version = "0.8.3", default-features = false, features = ["postgres"] }
tar = "0.4.43"
target-triple = "0.1.4"
tempfile = "3.17.1"
test-log = "0.2.17"
thiserror = "2.0.11"
tokio = "1.43.0"
tracing = "0.1.41"
tracing-indicatif = "0.3.9"
tracing-subscriber = "0.3.19"
url = "2.5.4"
zip = "2.2.2"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
